function C = dyn_C(q1,q2,q3,qd1,qd2,qd3)
%dyn_C
%    C = dyn_C(Q1,Q2,Q3,QD1,QD2,QD3)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    29-Jun-2026 16:44:33

t2 = sin(q3);
t3 = q2.*2.0;
t4 = q3.*2.0;
t5 = sin(t3);
t6 = q3+t3;
t8 = t3+t4;
t10 = t2.*2.808e-3;
t7 = sin(t6);
t9 = sin(t8);
t12 = t5.*9.05625e-3;
t11 = t7.*5.616e-3;
t13 = t7.*2.808e-3;
t14 = t9.*8.9856e-4;
t15 = t10+t13+t14;
t16 = t11+t12+t14;
t17 = qd1.*t15;
t18 = qd1.*t16;
C = reshape([-qd2.*t16-qd3.*t15,t18,t17,-t18,qd3.*t2.*(-5.616e-3),qd2.*t2.*5.616e-3,-t17,t2.*(qd2+qd3).*(-5.616e-3),0.0],[3,3]);
end
