function M = dyn_M(q1,q2,q3)
%dyn_M
%    M = dyn_M(Q1,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    29-Jun-2026 16:44:33

t2 = cos(q3);
t3 = q2.*2.0;
t4 = t2.*5.616e-3;
t5 = t4+1.79712e-3;
M = reshape([t4+cos(q3.*2.0+t3).*8.9856e-4+cos(q3+t3).*5.616e-3+cos(t3).*9.05625e-3+9.95481e-3,0.0,0.0,0.0,t2.*1.1232e-2+1.990962e-2,t5,0.0,t5,1.79712e-3],[3,3]);
end
