function J = dyn_J(q1,q2,q3)
%dyn_J
%    J = dyn_J(Q1,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    29-Jun-2026 16:44:34

t2 = cos(q1);
t3 = cos(q2);
t4 = sin(q1);
t5 = sin(q2);
t6 = q2+q3;
t7 = t3.*5.0;
t8 = cos(t6);
t9 = sin(t6);
t10 = -t2;
t12 = t5.*(3.0./2.0e+1);
t11 = t8.*4.0;
t13 = t8.*(3.0./2.5e+1);
t14 = t9.*(3.0./2.5e+1);
t15 = t7+t11;
t16 = t12+t14;
J = reshape([t4.*t15.*(-3.0./1.0e+2),t2.*t15.*(3.0./1.0e+2),0.0,0.0,0.0,1.0,t10.*t16,-t4.*t16,t3.*(3.0./2.0e+1)+t13,t4,t10,0.0,t2.*t9.*(-3.0./2.5e+1),t4.*t9.*(-3.0./2.5e+1),t13,t4,t10,0.0],[6,3]);
end
