function G = dyn_G(q1,q2,q3)
%dyn_G
%    G = dyn_G(Q1,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    29-Jun-2026 16:44:34

t2 = q2+q3;
t3 = cos(t2);
t4 = t3.*3.672864e-1;
G = [0.0;t4+cos(q2).*1.221345;t4];
end
